-- AUTOGENERATED by scripts/build_diagonal_glyph_atlas.py — do not edit.
-- 3.3.5a diagonal glyph atlas: pre-rotated ASCII chars in a TGA grid.
-- Consumed by MRT/DiagonalGlyphAtlas.lua at runtime.
MRT = MRT or {}
MRT.DiagonalGlyphAtlas = MRT.DiagonalGlyphAtlas or {}
local atlas = {
    file = "Interface\\AddOns\\MRT\\media\\MRT_DiagonalGlyphs.tga",
    width = 1024,
    height = 512,
    cell = 48,
    cols = 16,
    rows = 8,
    rotationDeg = 60,
    chars = {},  -- char (string) -> { col=, row= }
}
atlas.chars[" "] = { col = 0, row = 0 }
atlas.chars["!"] = { col = 1, row = 0 }
atlas.chars["\""] = { col = 2, row = 0 }
atlas.chars["#"] = { col = 3, row = 0 }
atlas.chars["$"] = { col = 4, row = 0 }
atlas.chars["%"] = { col = 5, row = 0 }
atlas.chars["&"] = { col = 6, row = 0 }
atlas.chars["'"] = { col = 7, row = 0 }
atlas.chars["("] = { col = 8, row = 0 }
atlas.chars[")"] = { col = 9, row = 0 }
atlas.chars["*"] = { col = 10, row = 0 }
atlas.chars["+"] = { col = 11, row = 0 }
atlas.chars[","] = { col = 12, row = 0 }
atlas.chars["-"] = { col = 13, row = 0 }
atlas.chars["."] = { col = 14, row = 0 }
atlas.chars["/"] = { col = 15, row = 0 }
atlas.chars["0"] = { col = 0, row = 1 }
atlas.chars["1"] = { col = 1, row = 1 }
atlas.chars["2"] = { col = 2, row = 1 }
atlas.chars["3"] = { col = 3, row = 1 }
atlas.chars["4"] = { col = 4, row = 1 }
atlas.chars["5"] = { col = 5, row = 1 }
atlas.chars["6"] = { col = 6, row = 1 }
atlas.chars["7"] = { col = 7, row = 1 }
atlas.chars["8"] = { col = 8, row = 1 }
atlas.chars["9"] = { col = 9, row = 1 }
atlas.chars[":"] = { col = 10, row = 1 }
atlas.chars[";"] = { col = 11, row = 1 }
atlas.chars["<"] = { col = 12, row = 1 }
atlas.chars["="] = { col = 13, row = 1 }
atlas.chars[">"] = { col = 14, row = 1 }
atlas.chars["?"] = { col = 15, row = 1 }
atlas.chars["@"] = { col = 0, row = 2 }
atlas.chars["A"] = { col = 1, row = 2 }
atlas.chars["B"] = { col = 2, row = 2 }
atlas.chars["C"] = { col = 3, row = 2 }
atlas.chars["D"] = { col = 4, row = 2 }
atlas.chars["E"] = { col = 5, row = 2 }
atlas.chars["F"] = { col = 6, row = 2 }
atlas.chars["G"] = { col = 7, row = 2 }
atlas.chars["H"] = { col = 8, row = 2 }
atlas.chars["I"] = { col = 9, row = 2 }
atlas.chars["J"] = { col = 10, row = 2 }
atlas.chars["K"] = { col = 11, row = 2 }
atlas.chars["L"] = { col = 12, row = 2 }
atlas.chars["M"] = { col = 13, row = 2 }
atlas.chars["N"] = { col = 14, row = 2 }
atlas.chars["O"] = { col = 15, row = 2 }
atlas.chars["P"] = { col = 0, row = 3 }
atlas.chars["Q"] = { col = 1, row = 3 }
atlas.chars["R"] = { col = 2, row = 3 }
atlas.chars["S"] = { col = 3, row = 3 }
atlas.chars["T"] = { col = 4, row = 3 }
atlas.chars["U"] = { col = 5, row = 3 }
atlas.chars["V"] = { col = 6, row = 3 }
atlas.chars["W"] = { col = 7, row = 3 }
atlas.chars["X"] = { col = 8, row = 3 }
atlas.chars["Y"] = { col = 9, row = 3 }
atlas.chars["Z"] = { col = 10, row = 3 }
atlas.chars["["] = { col = 11, row = 3 }
atlas.chars["\\"] = { col = 12, row = 3 }
atlas.chars["]"] = { col = 13, row = 3 }
atlas.chars["^"] = { col = 14, row = 3 }
atlas.chars["_"] = { col = 15, row = 3 }
atlas.chars["`"] = { col = 0, row = 4 }
atlas.chars["a"] = { col = 1, row = 4 }
atlas.chars["b"] = { col = 2, row = 4 }
atlas.chars["c"] = { col = 3, row = 4 }
atlas.chars["d"] = { col = 4, row = 4 }
atlas.chars["e"] = { col = 5, row = 4 }
atlas.chars["f"] = { col = 6, row = 4 }
atlas.chars["g"] = { col = 7, row = 4 }
atlas.chars["h"] = { col = 8, row = 4 }
atlas.chars["i"] = { col = 9, row = 4 }
atlas.chars["j"] = { col = 10, row = 4 }
atlas.chars["k"] = { col = 11, row = 4 }
atlas.chars["l"] = { col = 12, row = 4 }
atlas.chars["m"] = { col = 13, row = 4 }
atlas.chars["n"] = { col = 14, row = 4 }
atlas.chars["o"] = { col = 15, row = 4 }
atlas.chars["p"] = { col = 0, row = 5 }
atlas.chars["q"] = { col = 1, row = 5 }
atlas.chars["r"] = { col = 2, row = 5 }
atlas.chars["s"] = { col = 3, row = 5 }
atlas.chars["t"] = { col = 4, row = 5 }
atlas.chars["u"] = { col = 5, row = 5 }
atlas.chars["v"] = { col = 6, row = 5 }
atlas.chars["w"] = { col = 7, row = 5 }
atlas.chars["x"] = { col = 8, row = 5 }
atlas.chars["y"] = { col = 9, row = 5 }
atlas.chars["z"] = { col = 10, row = 5 }
atlas.chars["{"] = { col = 11, row = 5 }
atlas.chars["|"] = { col = 12, row = 5 }
atlas.chars["}"] = { col = 13, row = 5 }
atlas.chars["~"] = { col = 14, row = 5 }
MRT.DiagonalGlyphAtlas.data = atlas
